target 'FaithMeetsLove' do


pod 'GoogleSignIn'
#pod 'Firebase/Core'
pod 'FBSDKLoginKit'
pod 'Firebase/Core', '~> 5.9.0'
pod 'Firebase/Auth', '~> 5.9.0'
pod 'Firebase/Messaging', '~> 5.9.0'
pod 'Firebase/Database', '~> 5.9.0'
pod 'Firebase/RemoteConfig', '~> 5.9.0'
pod 'GoogleAppMeasurement', '~> 5.2.0'
pod 'Firebase/Firestore', '~> 5.9.0'
pod 'Firebase/Storage', '~> 5.9.0'
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'



  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
